<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OVJ75DL" failures="1" tests="3" name="Test" time="0.083" errors="0" timestamp="2022-11-06T14:29:52 IST">
  <testcase classname="RetryAnalyer.RunRetry" name="testcase1" time="0.017">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="RetryAnalyer.RunRetry" name="testcase1" time="0.002">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="RetryAnalyer.RunRetry" name="testcase1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryAnalyer.RunRetry.testcase1(RunRetry.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
</testsuite> <!-- Test -->
